model:
  name: convnext_tiny
  pretrained: true

train:
  batch_size: 64
  num_epochs: 100
  lr: 5e-5
  momentum: 0.9
  weight_decay: 1e-4
  img_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
