data:
  path: /content/MyOpenAnimalTracks/OpenAnimalTracks/cropped_imgs
  train_dir: /content/MyOpenAnimalTracks/classification/data/cropped_imgs/train
  val_dir: /content/MyOpenAnimalTracks/classification/data/cropped_imgs/val
  test_dir: /content/MyOpenAnimalTracks/classification/data/cropped_imgs/test

model:
  name: resnet50
  pretrained: True

train:
  batch_size: 128
  num_epochs: 50
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-4
  img_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]